### ISSUE TITLE
[1.15.2] Java version check incorrect

### ISSUE THREAD

**Issue by NielsPilgaard** [Darkhax-Minecraft/OldJavaWarning#7]
It seems the config value doesn't get properly, or the version compare is off, I was warned that my Java `1.8.0_241` was outdated, while the config checked for a minimum of `1.8.0_162`

Warning and config:
![billede](https://user-images.githubusercontent.com/21295394/78390368-b7828900-75e4-11ea-9cd9-57aef8d0f9ed.png)

**Comment by NielsPilgaard** [comment]
Any update on this issue? :)
The mod isn't really useable in it's current state, imo.

**Comment by PiggiesGoSqueal** [comment]
> 
> 
> Any update on this issue? :)
> The mod isn't really useable in it's current state, imo.

Do you know if this is an issue on 1.12.2 by any chance?

**Comment by NielsPilgaard** [comment]
This issue is not, but I'm not certain whether there are other issues on 1.12.2 :)

**Comment by Darkhax** [comment]
Sorry it took so long for this issue to be fixed. It was working completely fine locally so I was very confused. Turns out I left in some debug code which inverts the java version check so it would only warn users with a good version of Java. This has been fixed on 1.15.2 and will soon be fixed on 1.14.4 as well. The 1.12.2 version works fine and has been widely tested by over 100k users.
